"""add api_key to user

Revision ID: 57f12b2518cf
Revises: 8711b4aa4670
Create Date: 2025-11-13 15:59:01.703119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f12b2518cf'
down_revision = '8711b4aa4670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###

    # Optionally generate API keys for existing users here
    op.execute("UPDATE user SET api_key = '<default_value>' WHERE api_key IS NULL")

    # Make the column non-nullable after populating it
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('api_key', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
